<script lang="ts">
  import { Color } from '/src/ambient.d.ts';
  import type { Category, Post, Tag } from '/src/ambient.d.ts';

  let post = {title: "First post", dateAdded: "11/07/2024", tags: [{name: "AI", color: Color.red} as Tag], content: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus nullam eget felis eget nunc lobortis mattis aliquam faucibus. Sit amet massa vitae tortor condimentum lacinia quis vel. Tortor posuere ac ut consequat. Nisi porta lorem mollis aliquam ut porttitor leo a diam. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Sodales ut etiam sit amet nisl purus in mollis. Eu non diam phasellus vestibulum lorem sed risus ultricies. Lobortis mattis aliquam faucibus purus in massa tempor. At auctor urna nunc id cursus. Elit sed vulputate mi sit amet mauris commodo. A pellentesque sit amet porttitor. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Sit amet consectetur adipiscing elit ut. Consequat ac felis donec et odio pellentesque diam. Aenean pharetra magna ac placerat vestibulum lectus mauris.",

"Pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Aliquam eleifend mi in nulla. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Ut diam quam nulla porttitor massa. Accumsan in nisl nisi scelerisque eu ultrices. Ultricies tristique nulla aliquet enim tortor at auctor urna. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Magna fringilla urna porttitor rhoncus dolor purus non. Volutpat ac tincidunt vitae semper quis lectus nulla. Id diam maecenas ultricies mi. Lectus nulla at volutpat diam ut. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Feugiat nisl pretium fusce id.",

"Duis ultricies lacus sed turpis tincidunt. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Leo a diam sollicitudin tempor id eu nisl. Donec enim diam vulputate ut pharetra sit amet aliquam id. Aliquam ultrices sagittis orci a. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Ornare lectus sit amet est placerat. Ac odio tempor orci dapibus ultrices in. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Arcu ac tortor dignissim convallis aenean et tortor at. Posuere ac ut consequat semper viverra nam. Facilisis mauris sit amet massa vitae tortor condimentum. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Mattis aliquam faucibus purus in. Diam vulputate ut pharetra sit amet aliquam. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Mauris sit amet massa vitae tortor condimentum.",

"Sit amet facilisis magna etiam tempor orci eu. Dictum sit amet justo donec enim. Libero volutpat sed cras ornare arcu dui vivamus arcu. Phasellus vestibulum lorem sed risus ultricies tristique. Velit scelerisque in dictum non consectetur a. Nulla facilisi cras fermentum odio eu feugiat pretium. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Consectetur lorem donec massa sapien faucibus et molestie. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Morbi tempus iaculis urna id volutpat lacus laoreet. Adipiscing enim eu turpis egestas pretium. Justo donec enim diam vulputate ut. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Dictum sit amet justo donec enim diam vulputate. At risus viverra adipiscing at in tellus integer feugiat scelerisque.",

"In hac habitasse platea dictumst vestibulum. Feugiat nibh sed pulvinar proin gravida. Cras adipiscing enim eu turpis. A arcu cursus vitae congue mauris rhoncus aenean vel. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Suscipit tellus mauris a diam maecenas sed enim ut sem. Sodales ut eu sem integer vitae. Suspendisse in est ante in. Eget nullam non nisi est. Felis donec et odio pellentesque. Faucibus pulvinar elementum integer enim. Interdum varius sit amet mattis vulputate enim nulla aliquet. Purus sit amet volutpat consequat mauris nunc congue nisi. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Pharetra diam sit amet nisl suscipit adipiscing.",

"Aliquam purus sit amet luctus venenatis. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Tellus integer feugiat scelerisque varius morbi. Odio pellentesque diam volutpat commodo sed egestas. Vitae auctor eu augue ut lectus arcu bibendum at varius. Vulputate mi sit amet mauris commodo quis. Habitant morbi tristique senectus et netus et. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Condimentum lacinia quis vel eros donec ac odio tempor orci. Bibendum est ultricies integer quis auctor elit sed vulputate. Eu consequat ac felis donec et odio pellentesque. In arcu cursus euismod quis viverra. Ut sem viverra aliquet eget sit amet tellus cras. Gravida rutrum quisque non tellus orci ac auctor augue. Sagittis id consectetur purus ut faucibus pulvinar. Ac turpis egestas maecenas pharetra. Libero justo laoreet sit amet cursus sit amet.",

"Massa eget egestas purus viverra accumsan in nisl nisi. Nibh sed pulvinar proin gravida hendrerit lectus. Aenean euismod elementum nisi quis. Congue quisque egestas diam in arcu cursus. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Integer enim neque volutpat ac tincidunt vitae semper quis. Ultrices vitae auctor eu augue. Molestie nunc non blandit massa enim nec dui nunc. Duis convallis convallis tellus id interdum velit laoreet id donec. Nunc sed augue lacus viverra vitae congue eu. Molestie ac feugiat sed lectus vestibulum mattis. Viverra nam libero justo laoreet sit. Tellus in metus vulputate eu scelerisque. Nibh ipsum consequat nisl vel pretium lectus. Nulla facilisi cras fermentum odio eu. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Sagittis id consectetur purus ut. Adipiscing at in tellus integer feugiat scelerisque varius morbi.",

"Eu feugiat pretium nibh ipsum consequat nisl vel. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. In ante metus dictum at tempor commodo ullamcorper a. Sit amet porttitor eget dolor morbi non arcu. Et netus et malesuada fames ac. Rhoncus est pellentesque elit ullamcorper dignissim. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Aliquam etiam erat velit scelerisque in. Ac turpis egestas maecenas pharetra convallis. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Malesuada fames ac turpis egestas. Volutpat ac tincidunt vitae semper quis lectus nulla. Nec tincidunt praesent semper feugiat.",

"Risus feugiat in ante metus. Viverra accumsan in nisl nisi scelerisque eu ultrices. Cras sed felis eget velit aliquet sagittis. Quis vel eros donec ac odio tempor orci dapibus ultrices. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Vivamus at augue eget arcu dictum. Quam vulputate dignissim suspendisse in est ante in. Maecenas sed enim ut sem viverra. Cursus euismod quis viverra nibh cras pulvinar mattis. Magna sit amet purus gravida quis blandit turpis. Egestas egestas fringilla phasellus faucibus. Cursus in hac habitasse platea dictumst quisque sagittis purus. Pharetra vel turpis nunc eget. Id neque aliquam vestibulum morbi blandit. Libero id faucibus nisl tincidunt eget nullam.",

"Eget aliquet nibh praesent tristique. Aliquam nulla facilisi cras fermentum odio eu feugiat. Vel fringilla est ullamcorper eget nulla facilisi. Dolor sit amet consectetur adipiscing elit duis tristique. Dui accumsan sit amet nulla facilisi morbi tempus. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. In mollis nunc sed id semper. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Ante metus dictum at tempor commodo ullamcorper a lacus vestibulum. Amet purus gravida quis blandit turpis cursus in. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Tincidunt eget nullam non nisi. Aliquam etiam erat velit scelerisque in. Diam volutpat commodo sed egestas. Sed vulputate mi sit amet mauris commodo. Gravida quis blandit turpis cursus. Arcu cursus vitae congue mauris rhoncus aenean vel elit.",

"Mus mauris vitae ultricies leo integer. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Commodo elit at imperdiet dui accumsan sit amet nulla. Id diam vel quam elementum pulvinar. Non blandit massa enim nec dui nunc mattis. Bibendum est ultricies integer quis auctor elit sed. Netus et malesuada fames ac turpis egestas integer. Amet nulla facilisi morbi tempus iaculis urna id. Tempus urna et pharetra pharetra massa massa ultricies. Lectus magna fringilla urna porttitor rhoncus dolor purus. Donec massa sapien faucibus et molestie ac feugiat sed. Velit aliquet sagittis id consectetur.",

"Et malesuada fames ac turpis. Ac turpis egestas integer eget aliquet. Id velit ut tortor pretium viverra suspendisse potenti nullam. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Sed elementum tempus egestas sed sed risus. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Et ultrices neque ornare aenean. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Vitae aliquet nec ullamcorper sit. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Sed cras ornare arcu dui vivamus arcu. Risus pretium quam vulputate dignissim suspendisse. Maecenas pharetra convallis posuere morbi leo urna molestie at. Bibendum neque egestas congue quisque egestas diam in arcu. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.",

"Massa massa ultricies mi quis hendrerit. Risus commodo viverra maecenas accumsan. In nibh mauris cursus mattis molestie a iaculis. Lacinia quis vel eros donec ac odio. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Sed enim ut sem viverra aliquet eget sit amet tellus. Adipiscing enim eu turpis egestas pretium aenean. Nam aliquam sem et tortor. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Purus in mollis nunc sed. Nunc mattis enim ut tellus elementum sagittis. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Neque sodales ut etiam sit amet nisl. Eget sit amet tellus cras adipiscing. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Id aliquet lectus proin nibh nisl condimentum id. Urna molestie at elementum eu facilisis sed odio morbi.",

"Et ligula ullamcorper malesuada proin libero nunc consequat. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Posuere lorem ipsum dolor sit amet consectetur. Enim nunc faucibus a pellentesque sit amet. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Cursus eget nunc scelerisque viverra mauris. Laoreet sit amet cursus sit amet dictum sit amet. Diam in arcu cursus euismod. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Sed cras ornare arcu dui. Mattis molestie a iaculis at erat. Accumsan sit amet nulla facilisi morbi tempus. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Amet nisl suscipit adipiscing bibendum est ultricies. Nisi est sit amet facilisis magna etiam tempor orci eu. Sollicitudin nibh sit amet commodo. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Amet est placerat in egestas erat imperdiet sed euismod. Metus dictum at tempor commodo ullamcorper a.",

"Lacinia at quis risus sed vulputate odio ut enim. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Integer vitae justo eget magna fermentum iaculis eu non diam. Urna nunc id cursus metus aliquam eleifend mi in. Sed libero enim sed faucibus turpis in eu. At in tellus integer feugiat scelerisque varius morbi enim nunc. Nullam vehicula ipsum a arcu. Et netus et malesuada fames ac. Leo duis ut diam quam nulla. Turpis egestas maecenas pharetra convallis posuere. Tristique nulla aliquet enim tortor at auctor urna nunc id. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Nulla facilisi etiam dignissim diam quis enim lobortis. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Sed odio morbi quis commodo odio aenean sed. Odio tempor orci dapibus ultrices in iaculis nunc. Sem integer vitae justo eget magna fermentum iaculis eu non.",

"Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Sit amet facilisis magna etiam tempor orci. Volutpat est velit egestas dui id. Aliquet risus feugiat in ante metus dictum. Urna nunc id cursus metus aliquam eleifend mi in nulla. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Dui faucibus in ornare quam viverra orci sagittis. Quis imperdiet massa tincidunt nunc pulvinar. Urna molestie at elementum eu facilisis sed odio morbi quis. Diam phasellus vestibulum lorem sed risus. Bibendum ut tristique et egestas. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Urna duis convallis convallis tellus id.",

"Scelerisque purus semper eget duis at. At lectus urna duis convallis convallis. Nunc vel risus commodo viverra maecenas. Sed risus pretium quam vulputate. Id interdum velit laoreet id. Massa eget egestas purus viverra accumsan. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Integer enim neque volutpat ac. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Mauris rhoncus aenean vel elit. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Vulputate enim nulla aliquet porttitor lacus luctus. Morbi quis commodo odio aenean sed adipiscing diam. Orci phasellus egestas tellus rutrum. Quis eleifend quam adipiscing vitae. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Augue ut lectus arcu bibendum at varius vel pharetra.",

"Lectus arcu bibendum at varius vel pharetra vel turpis. Orci dapibus ultrices in iaculis nunc sed. Morbi tempus iaculis urna id volutpat. Morbi tristique senectus et netus et. Duis ultricies lacus sed turpis tincidunt id. Scelerisque felis imperdiet proin fermentum leo. Sed velit dignissim sodales ut eu sem integer vitae. At tellus at urna condimentum mattis pellentesque id. Tincidunt lobortis feugiat vivamus at augue eget arcu. Quam viverra orci sagittis eu volutpat odio facilisis. Mi in nulla posuere sollicitudin aliquam. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Rutrum quisque non tellus orci. Nibh sed pulvinar proin gravida. Pellentesque adipiscing commodo elit at. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Non diam phasellus vestibulum lorem sed risus ultricies. Adipiscing elit ut aliquam purus.",

"Vulputate dignissim suspendisse in est. Eu lobortis elementum nibh tellus. Urna molestie at elementum eu facilisis sed odio morbi quis. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Fringilla ut morbi tincidunt augue. Rhoncus urna neque viverra justo. Convallis convallis tellus id interdum velit. Magna etiam tempor orci eu. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Viverra adipiscing at in tellus integer. Diam vulputate ut pharetra sit. Gravida rutrum quisque non tellus orci ac auctor augue. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum.",

"A diam maecenas sed enim ut sem. Semper eget duis at tellus at urna condimentum mattis. Mauris in aliquam sem fringilla ut. Quam elementum pulvinar etiam non. Sed viverra ipsum nunc aliquet bibendum. Enim nulla aliquet porttitor lacus luctus accumsan. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam purus. Feugiat pretium nibh ipsum consequat nisl. Nam aliquam sem et tortor consequat id porta nibh. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Tristique risus nec feugiat in fermentum. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Sit amet cursus sit amet dictum sit amet justo donec. Ut faucibus pulvinar elementum integer enim neque volutpat. Vel quam elementum pulvinar etiam non quam lacus. Consectetur purus ut faucibus pulvinar elementum. Justo nec ultrices dui sapien eget mi. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat."]}
</script>

<svelte:head>
	<title>Post</title>
	<meta name="description" content="Post" />
</svelte:head>

<section class="mt-16 flex flex-col justify-center items-center">
  <h1 class="self-start text-4xl font-semibold text-justify">{post.title}</h1>
  <div class="mt-2 mb-8 flex self-start font-serif">
    <p>
      {post.dateAdded}
    </p>
    <div class="pl-24 flex flex-row gap-4 text-md">
      Tags:
      {#each post.tags as tag}
        <a class="rounded-2xl px-4 text-primary bg-{tag.color}-950 text-center" href="posts&category={tag.name}">
          {tag.name}
        </a>
      {/each}
    </div>
  </div>
  <!-- for section in database, render each -->
  {#each post.content as content}
    <section class="mt-[1lh] w-[70ch] text-pretty text-justify leading-normal text-xl font-serif">
      {content}
    </section>
  {/each}
</section>
